affinity: {}
fullnameOverride: ''
image:
  args:
    e2term: service-ricplt-e2term-r4-e2term-sctp-alpha.ricplt.svc.cluster.local
    mcc: 724
    mnc: 11
    nodebid: 1
    port: 36422
  command: e2sim
  pullPolicy: Always
  repository: registry-docker-registry.registry.svc.cluster.local:5000/e2sim-rc
  tag: 'TNSM-25'
nameOverride: ''
nodeSelector:
  kubernetes.io/hostname: node3
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
service:
  portSimulator: 8081
  portO1: 8090
  tls: []
  type: ClusterIP
  typehandover: NodePort
tolerations: []