apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e2sim-helm.fullname" . }}
  labels:
    {{- include "e2sim-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "e2sim-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "e2sim-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: simulator
              containerPort: 8081
              protocol: TCP
            - name: o1
              containerPort: 8090
              protocol: TCP
          command: ["{{ .Values.image.command }}"]
          args: ["{{ .Values.image.args.e2term }}", "--mcc", "{{ .Values.image.args.mcc }}", "--mnc", "{{ .Values.image.args.mnc }}", "--nodebid", "{{ .Values.image.args.nodebid }}", "-p", "{{ .Values.image.args.port }}", "--ue_mgr", "{{ .Values.image.args.ue_mgr }}"]          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
