/**
* E2 Node UE API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_E2Node_get_200_response.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_E2Node_get_200_response::_E2Node_get_200_response()
{
    m_GNBId = "";
    m_GNBIdIsSet = false;
    
}

void _E2Node_get_200_response::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _E2Node_get_200_response::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _E2Node_get_200_response::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_E2Node_get_200_response" : pathPrefix;

        
    return success;
}

bool _E2Node_get_200_response::operator==(const _E2Node_get_200_response& rhs) const
{
    return
    
    
    
    ((!gNBIdIsSet() && !rhs.gNBIdIsSet()) || (gNBIdIsSet() && rhs.gNBIdIsSet() && getGNBId() == rhs.getGNBId()))
    
    ;
}

bool _E2Node_get_200_response::operator!=(const _E2Node_get_200_response& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _E2Node_get_200_response& o)
{
    j = nlohmann::json::object();
    if(o.gNBIdIsSet())
        j["gNBId"] = o.m_GNBId;
    
}

void from_json(const nlohmann::json& j, _E2Node_get_200_response& o)
{
    if(j.find("gNBId") != j.end())
    {
        j.at("gNBId").get_to(o.m_GNBId);
        o.m_GNBIdIsSet = true;
    } 
    
}

std::string _E2Node_get_200_response::getGNBId() const
{
    return m_GNBId;
}
void _E2Node_get_200_response::setGNBId(std::string const& value)
{
    m_GNBId = value;
    m_GNBIdIsSet = true;
}
bool _E2Node_get_200_response::gNBIdIsSet() const
{
    return m_GNBIdIsSet;
}
void _E2Node_get_200_response::unsetGNBId()
{
    m_GNBIdIsSet = false;
}


} // namespace org::openapitools::server::model

