/**
* E2 Node UE API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * _E2Node_get_200_response.h
 *
 * 
 */

#ifndef _E2Node_get_200_response_H_
#define _E2Node_get_200_response_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  _E2Node_get_200_response
{
public:
    _E2Node_get_200_response();
    virtual ~_E2Node_get_200_response() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const _E2Node_get_200_response& rhs) const;
    bool operator!=(const _E2Node_get_200_response& rhs) const;

    /////////////////////////////////////////////
    /// _E2Node_get_200_response members

    /// <summary>
    /// 
    /// </summary>
    std::string getGNBId() const;
    void setGNBId(std::string const& value);
    bool gNBIdIsSet() const;
    void unsetGNBId();

    friend  void to_json(nlohmann::json& j, const _E2Node_get_200_response& o);
    friend  void from_json(const nlohmann::json& j, _E2Node_get_200_response& o);
protected:
    std::string m_GNBId;
    bool m_GNBIdIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* _E2Node_get_200_response_H_ */
