/**
* E2 Node UE API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "_UEs_get_200_response.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

_UEs_get_200_response::_UEs_get_200_response()
{
    m_ImsisActiveIsSet = false;
    m_Message = "";
    m_MessageIsSet = false;
    
}

void _UEs_get_200_response::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool _UEs_get_200_response::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool _UEs_get_200_response::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "_UEs_get_200_response" : pathPrefix;

         
    if (imsisActiveIsSet())
    {
        const std::vector<std::string>& value = m_ImsisActive;
        const std::string currentValuePath = _pathPrefix + ".imsisActive";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const std::string& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
        
    return success;
}

bool _UEs_get_200_response::operator==(const _UEs_get_200_response& rhs) const
{
    return
    
    
    
    ((!imsisActiveIsSet() && !rhs.imsisActiveIsSet()) || (imsisActiveIsSet() && rhs.imsisActiveIsSet() && getImsisActive() == rhs.getImsisActive())) &&
    
    
    ((!messageIsSet() && !rhs.messageIsSet()) || (messageIsSet() && rhs.messageIsSet() && getMessage() == rhs.getMessage()))
    
    ;
}

bool _UEs_get_200_response::operator!=(const _UEs_get_200_response& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const _UEs_get_200_response& o)
{
    j = nlohmann::json::object();
    if(o.imsisActiveIsSet() || !o.m_ImsisActive.empty())
        j["imsisActive"] = o.m_ImsisActive;
    if(o.messageIsSet())
        j["message"] = o.m_Message;
    
}

void from_json(const nlohmann::json& j, _UEs_get_200_response& o)
{
    if(j.find("imsisActive") != j.end())
    {
        j.at("imsisActive").get_to(o.m_ImsisActive);
        o.m_ImsisActiveIsSet = true;
    } 
    if(j.find("message") != j.end())
    {
        j.at("message").get_to(o.m_Message);
        o.m_MessageIsSet = true;
    } 
    
}

std::vector<std::string> _UEs_get_200_response::getImsisActive() const
{
    return m_ImsisActive;
}
void _UEs_get_200_response::setImsisActive(std::vector<std::string> const& value)
{
    m_ImsisActive = value;
    m_ImsisActiveIsSet = true;
}
bool _UEs_get_200_response::imsisActiveIsSet() const
{
    return m_ImsisActiveIsSet;
}
void _UEs_get_200_response::unsetImsisActive()
{
    m_ImsisActiveIsSet = false;
}
std::string _UEs_get_200_response::getMessage() const
{
    return m_Message;
}
void _UEs_get_200_response::setMessage(std::string const& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}
bool _UEs_get_200_response::messageIsSet() const
{
    return m_MessageIsSet;
}
void _UEs_get_200_response::unsetMessage()
{
    m_MessageIsSet = false;
}


} // namespace org::openapitools::server::model

